#
# Important: Filename is 'pytest_config.ini" and not the defualt "pytest.ini"
# So it must be activated via commandline argument, e.g.:
#
#   pytest -c pytest_config.ini
#
# This is needed, to catch import errors! Otherwise you will see only something
# like this (on every start):
#   pytest.py: error: unrecognized arguments: --reuse-db --nomigrations...
# The Problem is: PyTest will not find plugins if the test package will have
# some import errors!
#
# The options '--reuse-db' and '--create-db' are not set here
# they will be applied in Makefile!
#
# http://doc.pytest.org/en/latest/customize.html#builtin-configuration-file-options
# https://pytest-django.readthedocs.io/en/latest/

[pytest]
DJANGO_SETTINGS_MODULE=apps.settings.test_ci
testpaths = src
# http://doc.pytest.org/en/latest/customize.html#confval-norecursedirs
cache_dir=/tmp
norecursedirs =
    .*
    .virtualenv_docker
    .virtualenv_local
    __pycache__
    frontend
    reports
addopts =
    --verbose
    #--reuse-db
    #--create-db
    --nomigrations
    --showlocals
    #--trace-config
    #--doctest-modules
    --cov-report xml:reports/coverage.xml
    --cov-report html:reports/
    --cov-config pytest_config.ini
    --no-cov-on-fail
    # Do not cut tracebacks (somethimes helpfull):
    #--full-trace
    # exit after 2 failures:
    --maxfail=2
    # per-test capturing method: one of fd|sys|no:
    #--capture=no
    # run the last failures first:
    --failed-first

# coverage
[run]
source = src
branch = True
data_file = /tmp/.coverage
omit =
    */migrations/*
    #*/management/*
    #*/tests/*
    #*/test*.py
    #*admin.py
    #*/forms.py
    #*/widgets.py
    *settings.py
    */settings/*.py
    */wsgi.py
